services:
  # ── MongoDB ──
  mongo:
    image: mongo:7
    container_name: loginpage-mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  # ── Backend App ──
  app:
    build: ./backend
    container_name: loginpage-app
    restart: unless-stopped
    ports:
      - "5000:3000"
    depends_on:
      - mongo
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/loginpage
      SESSION_SECRET: ${JWT_SECRET:-mysceretkey123}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL:-http://localhost:5000/auth/google/callback}

  # ── Frontend App ──
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: loginpage-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - app

volumes:
  mongo-data:
